version: "3.8"

services:
  tero-compressor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: tero-compressor
    volumes:
      - .:/app
    restart: unless-stopped
